* =outline-ivy=

This repository serves as a mirror of /ekaschalk/'s excellent package [[https://github.com/ekaschalk/.spacemacs.d/blob/master/layers/personal/local/outline-ivy/outline-ivy.el][outline-ivy]].
The mirror was created due to the lack of any official, standalone repository
for =outline-ivy=.

Any further commits will probably contain my own, personal changes. Also there
is no guarantee that this repository is kept up-to-date with /ekaschalk/'s
version.

** Installation

The easiest way to install is through [[https://github.com/jwiegley/use-package][use-package]]:

#+BEGIN_SRC emacs-lisp
(use-package outline-ivy
  :ensure nil
  :load-path "packages/outline-ivy"
  :bind (:map outline-minor-mode-map
              ("s-o" . oi-jump)))
#+END_SRC

Above is my personal configuration. Adjust it to suit your needs.

** License

*Like /ekaschalk/'s original code, it is licensed under the MIT license:*

The MIT License (MIT)

Copyright (c) 2016-2017 Eric Kaschalk

Permission is hereby granted, free of charge, to any person obtaining
a copy of this software and associated documentation files (the
"Software"), to deal in the Software without restriction, including
without limitation the rights to use, copy, modify, merge, publish,
distribute, sublicense, and/or sell copies of the Software, and to
permit persons to whom the Software is furnished to do so, subject to
the following conditions:

The above copyright notice and this permission notice shall be
included in all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY
CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
